import xml.etree.ElementTree as ET
import sys
import os
import re # Import regular expressions
from collections import defaultdict

# --- Constants ---
# Android namespace - needed for XML attributes like 'android:name'
NS = {'android': 'http://schemas.android.com/apk/res/android'}
# API level 31 (Android 12) is where the 'exported' rules changed significantly
ANDROID_12_API_LEVEL = 31

# ANSI Colors for beautiful output
CLR_RESET = "\033[0m"
CLR_RED = "\033[91m"
CLR_GREEN = "\033[92m"
CLR_YELLOW = "\033[93m"
CLR_BLUE = "\033[94m"
CLR_MAGENTA = "\033[95m"
CLR_CYAN = "\033[96m"
CLR_BOLD = "\033[1m"
CLR_HEADER = CLR_BOLD + CLR_CYAN
CLR_WARN = CLR_BOLD + CLR_RED
CLR_PERM = CLR_YELLOW
CLR_COMPONENT = CLR_BOLD
CLR_PARAM = CLR_MAGENTA

# --- Helper Functions ---

def get_target_sdk_version(root):
    """Grabs the target SDK version from the manifest."""
    uses_sdk = root.find('./uses-sdk', namespaces=NS)
    if uses_sdk is not None:
        target_sdk_str = uses_sdk.get(f"{{{NS['android']}}}targetSdkVersion")
        if target_sdk_str:
            try:
                return int(target_sdk_str)
            except ValueError:
                print(f"{CLR_YELLOW}Warning:{CLR_RESET} Invalid targetSdkVersion '{target_sdk_str}'. Assuming older Android rules.", file=sys.stderr)
                return ANDROID_12_API_LEVEL - 1 # Fallback
    print(f"{CLR_YELLOW}Warning:{CLR_RESET} targetSdkVersion not found. Assuming older Android rules.", file=sys.stderr)
    return ANDROID_12_API_LEVEL - 1 # Fallback

def get_application_permission(root):
    """Checks if the whole app has a default permission set."""
    application = root.find('./application', namespaces=NS)
    if application is not None:
        return application.get(f"{{{NS['android']}}}permission")
    return None

def find_manifest_file(base_dir):
    """Locates AndroidManifest.xml within the apktool directory."""
    manifest_path = os.path.join(base_dir, 'AndroidManifest.xml')
    if not os.path.isfile(manifest_path):
        alt_manifest_path = os.path.join(base_dir, 'base', 'AndroidManifest.xml')
        if os.path.isfile(alt_manifest_path):
             print(f"{CLR_YELLOW}Info:{CLR_RESET} Using manifest from 'base' subdirectory.", file=sys.stderr)
             return alt_manifest_path
        else:
             return None
    return manifest_path

def find_smali_files(base_dir, class_name):
    """Locates potential Smali file(s) for a given Java class name."""
    smali_files_found = []
    if not class_name or '.' not in class_name: # Basic validation
        return smali_files_found

    # Convert com.example.Class$Inner -> com/example/Class$Inner.smali
    relative_path = class_name.replace('.', '/') + '.smali'

    # Search in common Smali directories generated by apktool
    for smali_dir_name in os.listdir(base_dir):
        if smali_dir_name.startswith('smali'):
            potential_path = os.path.join(base_dir, smali_dir_name, relative_path)
            if os.path.isfile(potential_path):
                smali_files_found.append(potential_path)

    return smali_files_found

# --- Smali Analysis for Parameters (Heuristic) ---

# Regex to find 'const-string reg, "value"'
RE_CONST_STRING = re.compile(r'^\s*const-string\s+(v\d+|p\d+),\s+"([^"]+)"')
# Regex to find invokes of Uri.getQueryParameter(String)
RE_GET_QUERY_PARAM = re.compile(r'^\s*invoke-\w+\s+\{(?P<regs>.*)\},\s+Landroid/net/Uri;->getQueryParameter\(Ljava/lang/String;\)Ljava/lang/String;')

def find_query_parameters_in_smali(smali_path):
    """Scans a Smali file for strings used with getQueryParameter (heuristic)."""
    potential_params = set()
    # Track the last string loaded into registers within the current method scope
    register_string_map = {}
    in_method = False

    try:
        with open(smali_path, 'r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                line = line.strip()

                # Reset register map at the start of a new method
                if line.startswith('.method'):
                    register_string_map = {}
                    in_method = True
                elif line.startswith('.end method'):
                    register_string_map = {}
                    in_method = False
                    continue # Don't process lines after method ends until next method

                if not in_method:
                    continue

                # Track strings loaded into registers
                match_const = RE_CONST_STRING.match(line)
                if match_const:
                    register = match_const.group(1)
                    string_literal = match_const.group(2)
                    # Store the most recent string value for this register in this scope
                    register_string_map[register] = string_literal
                    continue # Move to next line

                # Check for getQueryParameter call
                match_invoke = RE_GET_QUERY_PARAM.match(line)
                if match_invoke:
                    # Extract registers used in the invoke instruction
                    # The string parameter is usually the *last* register before the Uri object register
                    # Example: {p0, p1, v0} -> p0=this, p1=Uri, v0=String
                    # Example: {v1, v2} -> v1=Uri, v2=String
                    # We need the register holding the string (parameter name)
                    regs_involved = [r.strip() for r in match_invoke.group('regs').split(',')]
                    if len(regs_involved) >= 2:
                        # Heuristic: Assume the last register listed holds the string param name
                        param_name_register = regs_involved[-1]

                        # Check if we recently loaded a string into this register
                        if param_name_register in register_string_map:
                            potential_param_name = register_string_map[param_name_register]
                            # Basic sanity check - avoid excessively long strings or obvious non-param names?
                            if potential_param_name and len(potential_param_name) < 100 and not potential_param_name.startswith('L'):
                                potential_params.add(potential_param_name)
                            # Optionally clear the mapping for this reg after use? Maybe not needed.
                        # else: parameter name wasn't loaded via const-string immediately before?

    except FileNotFoundError:
        pass # Silently ignore if the file doesn't exist
    except Exception as e:
        print(f"{CLR_YELLOW}Warning:{CLR_RESET} Error reading Smali file {smali_path}: {e}", file=sys.stderr)

    return potential_params


# --- Data Extraction Functions ---

def extract_deeplinks(root):
    """Parses the manifest to find deeplink URIs."""
    # (No changes needed in this function itself from the previous version)
    deeplinks = []
    for component_tag in ['activity', 'activity-alias']:
        for component in root.findall(f".//application/{component_tag}", namespaces=NS):
            component_name = component.get(f"{{{NS['android']}}}name", "Unknown Component")
            for intent_filter in component.findall('./intent-filter', namespaces=NS):
                has_view_action = any(
                    action.get(f"{{{NS['android']}}}name") == 'android.intent.action.VIEW'
                    for action in intent_filter.findall('./action', namespaces=NS)
                )
                has_default_category = any(
                    cat.get(f"{{{NS['android']}}}name") == 'android.intent.category.DEFAULT'
                    for cat in intent_filter.findall('./category', namespaces=NS)
                )
                has_browsable_category = any(
                    cat.get(f"{{{NS['android']}}}name") == 'android.intent.category.BROWSABLE'
                    for cat in intent_filter.findall('./category', namespaces=NS)
                )

                if has_view_action and has_default_category:
                    for data in intent_filter.findall('./data', namespaces=NS):
                        scheme = data.get(f"{{{NS['android']}}}scheme")
                        host = data.get(f"{{{NS['android']}}}host")
                        port = data.get(f"{{{NS['android']}}}port")
                        path = data.get(f"{{{NS['android']}}}path")
                        path_prefix = data.get(f"{{{NS['android']}}}pathPrefix")
                        path_pattern = data.get(f"{{{NS['android']}}}pathPattern")
                        mime_type = data.get(f"{{{NS['android']}}}mimeType")

                        uri_pattern_str = ""
                        path_used = ""

                        if scheme:
                            uri_pattern_str = f"{scheme}://"
                            if host: uri_pattern_str += host
                            if port: uri_pattern_str += f":{port}"
                            if path:
                                uri_pattern_str += path
                                path_used = "path"
                            elif path_prefix:
                                uri_pattern_str += path_prefix + "*"
                                path_used = "pathPrefix"
                            elif path_pattern:
                                uri_pattern_str += "/" + path_pattern + " (pattern)"
                                path_used = "pathPattern"
                            else:
                                uri_pattern_str += "/"

                            deeplinks.append({
                                'uri_pattern': uri_pattern_str,
                                'scheme': scheme, 'host': host,
                                'path_info': path or path_prefix or path_pattern,
                                'path_type': path_used,
                                'component': component_name,
                                'mime_type': mime_type,
                                'is_browsable': has_browsable_category,
                                'potential_params': set() # Initialize placeholder for params
                            })
                        elif mime_type and not scheme:
                             deeplinks.append({
                                'uri_pattern': f"MIME Type: {mime_type}",
                                'scheme': None, 'host': None, 'path_info': None, 'path_type': None,
                                'component': component_name,
                                'mime_type': mime_type,
                                'is_browsable': False,
                                'potential_params': set() # Initialize placeholder
                            })
    return deeplinks

def extract_components_info(root, target_sdk, app_permission):
    """Gets info about all components: type, name, export status, protection."""
    # (No changes needed in this function itself from the previous version)
    components_info = []
    component_tags = ['activity', 'service', 'receiver', 'provider', 'activity-alias']
    for component_type_tag in component_tags:
        effective_component_type = 'activity' if component_type_tag == 'activity-alias' else component_type_tag
        components = root.findall(f".//application/{component_type_tag}", namespaces=NS)
        for component in components:
            component_name = component.get(f"{{{NS['android']}}}name")
            if not component_name:
                if component_type_tag == 'activity-alias':
                    target = component.get(f"{{{NS['android']}}}targetActivity")
                    component_name = f"Alias for {target}" if target else f"Unnamed {component_type_tag}"
                else:
                    component_name = f"Unnamed {component_type_tag}"
            exported_attr = component.get(f"{{{NS['android']}}}exported")
            intent_filters = component.findall('./intent-filter', namespaces=NS)
            is_exported = False
            reason_exported = "Not Exported (Default)"
            if exported_attr is not None:
                is_exported = exported_attr.lower() == 'true'
                reason_exported = f"Explicitly {'Exported' if is_exported else 'Not Exported'} ({exported_attr})"
            else:
                if target_sdk >= ANDROID_12_API_LEVEL:
                    is_exported = False
                    reason_exported = f"Default Not Exported (targetSdk >= {ANDROID_12_API_LEVEL})"
                    if intent_filters:
                         reason_exported += f" {CLR_WARN}[INVALID Manifest - requires explicit exported]{CLR_RESET}"
                else:
                    if effective_component_type == 'provider':
                        is_exported = True
                        reason_exported = f"Default Exported (targetSdk < {ANDROID_12_API_LEVEL}, Provider)"
                    elif intent_filters:
                        is_exported = True
                        reason_exported = f"Implicitly Exported (targetSdk < {ANDROID_12_API_LEVEL}, has filters)"
                    else:
                        is_exported = False
                        reason_exported = f"Default Not Exported (targetSdk < {ANDROID_12_API_LEVEL}, no filters)"
            comp_perm = component.get(f"{{{NS['android']}}}permission")
            read_perm = component.get(f"{{{NS['android']}}}readPermission") if effective_component_type == 'provider' else None
            write_perm = component.get(f"{{{NS['android']}}}writePermission") if effective_component_type == 'provider' else None
            permissions_found = [p for p in [comp_perm, read_perm, write_perm, app_permission] if p]
            is_protected = bool(permissions_found)
            components_info.append({
                'name': component_name, 'type': effective_component_type,
                'is_exported': is_exported, 'export_reason': reason_exported,
                'is_protected': is_protected, 'permissions': permissions_found
            })
    return components_info

def extract_custom_permissions(root):
    """Finds custom permissions defined in the manifest."""
    # (No changes needed in this function itself from the previous version)
    custom_permissions = []
    for perm in root.findall('./permission', namespaces=NS):
        name = perm.get(f"{{{NS['android']}}}name")
        level = perm.get(f"{{{NS['android']}}}protectionLevel", "normal")
        label = perm.get(f"{{{NS['android']}}}label", "")
        desc = perm.get(f"{{{NS['android']}}}description", "")
        if name:
            custom_permissions.append({
                'name': name, 'protectionLevel': level, 'label': label, 'description': desc
            })
    return custom_permissions

# --- Output Formatting ---

def format_output(deeplinks, components_info, custom_permissions, target_sdk):
    """Creates the 'beautiful' console output."""

    print("\n" + CLR_HEADER + "+--------------------------------------+" + CLR_RESET)
    print(CLR_HEADER + "|   Android Attack Surface Analyzer    |" + CLR_RESET)
    print(CLR_HEADER + f"| Target SDK: {target_sdk:<24} |" + CLR_RESET)
    print(CLR_HEADER + "+--------------------------------------+" + CLR_RESET)

    # --- Deeplinks ---
    print("\n" + CLR_BOLD + CLR_MAGENTA + "[+] Deeplinks & URI Handlers:" + CLR_RESET)
    print(CLR_MAGENTA + "------------------------------" + CLR_RESET)
    if deeplinks:
        # Sort deeplinks for consistent output
        sorted_deeplinks = sorted(deeplinks, key=lambda x: x['uri_pattern'])
        for link in sorted_deeplinks:
            if link['scheme']:
                browsable_tag = f" {CLR_CYAN}[Browsable]{CLR_RESET}" if link['is_browsable'] else ""
                print(f"  {CLR_GREEN}{link['uri_pattern']}{CLR_RESET}{browsable_tag}")

                # Add note about path type if applicable
                if link['path_type'] == 'pathPrefix':
                    print(f"    {CLR_YELLOW}↳ Path Note: '*' indicates Path Prefix match (anything can follow path){CLR_RESET}")
                elif link['path_type'] == 'pathPattern':
                     print(f"    {CLR_YELLOW}↳ Path Note: Uses Pattern matching{CLR_RESET}")
                elif link['path_type'] == 'path':
                     print(f"    {CLR_YELLOW}↳ Path Note: Requires exact path match{CLR_RESET}")

                print(f"    ↳ Component: {CLR_COMPONENT}{link['component']}{CLR_RESET}")
                if link['host']: print(f"    ↳ Host: {link['host']}")
                if link['mime_type']: print(f"    ↳ MIME Type also: {link['mime_type']}")
                # Print potential parameters if found
                if link['potential_params']:
                    params_str = ', '.join(sorted(list(link['potential_params'])))
                    print(f"    ↳ {CLR_PARAM}Potential Params: {params_str}{CLR_RESET}")

            elif link['mime_type']: # Handle mimeType triggers separately
                 print(f"  {CLR_GREEN}MIME Type: {link['mime_type']}{CLR_RESET}")
                 print(f"    ↳ Component: {CLR_COMPONENT}{link['component']}{CLR_RESET}")

    else:
        print("  None found.")

    print(f"\n{CLR_YELLOW}Disclaimer:{CLR_RESET} Potential Params are hints from basic Smali code scanning.")
    print(f"          They may be incomplete or inaccurate due to obfuscation or complex code.")

    # --- Exported Components (Grouped by Type) ---
    exported_by_type = defaultdict(list)
    for comp in components_info:
        if comp['is_exported']:
            exported_by_type[comp['type']].append(comp)

    component_types_order = ['activity', 'service', 'receiver', 'provider']

    for comp_type in component_types_order:
        title_type = comp_type.capitalize()
        if comp_type == 'activity': title_type += " / Alias"

        print(f"\n{CLR_BOLD}{CLR_BLUE}[+] Exported {title_type}s:{CLR_RESET}")
        print(CLR_BLUE + "------------------------------------" + CLR_RESET)
        exported_list = exported_by_type[comp_type]
        if exported_list:
            for comp in sorted(exported_list, key=lambda x: x['name']):
                print(f"  {CLR_COMPONENT}{comp['name']}{CLR_RESET}")
                reason_clean = comp['export_reason'].replace(CLR_WARN,"").replace(CLR_RESET,"")
                print(f"    ↳ Exported: {reason_clean}")
                if comp['is_protected']:
                    perms_str = f"{CLR_PERM}" + f"{CLR_RESET}, {CLR_PERM}".join(comp['permissions']) + f"{CLR_RESET}"
                    print(f"    ↳ {CLR_GREEN}Protected by: {perms_str}")
                else:
                    print(f"    ↳ {CLR_WARN}[ ⚠️ UNPROTECTED ]{CLR_RESET}")
        else:
            print("  None found.")

    # --- Custom Permissions ---
    print("\n" + CLR_BOLD + CLR_YELLOW + "[+] Custom Permissions Defined:" + CLR_RESET)
    print(CLR_YELLOW + "------------------------------" + CLR_RESET)
    if custom_permissions:
        for perm in sorted(custom_permissions, key=lambda x: x['name']):
            level = perm['protectionLevel']
            level_color = CLR_GREEN
            if 'dangerous' in level: level_color = CLR_RED
            elif 'signature' in level: level_color = CLR_CYAN
            elif 'normal' in level: level_color = CLR_MAGENTA

            print(f"  {CLR_PERM}{perm['name']}{CLR_RESET}")
            print(f"    ↳ Protection Level: {level_color}{level}{CLR_RESET}")
    else:
        print("  None found.")

    print("\n" + CLR_HEADER + "+------------------- Analysis Complete --------------------+" + CLR_RESET + "\n")


# --- Main Analysis Logic ---

def analyze_apktool_directory(dir_path):
    """Orchestrates the analysis of the decompiled directory."""
    print(f"{CLR_CYAN}Starting analysis of directory: {dir_path}{CLR_RESET}")

    manifest_path = find_manifest_file(dir_path)
    if not manifest_path:
        print(f"{CLR_RED}Error: AndroidManifest.xml not found in '{dir_path}' or common subdirectories. Cannot proceed.{CLR_RESET}")
        return

    print(f"{CLR_CYAN}Found Manifest: {manifest_path}{CLR_RESET}")

    try:
        # Parse the XML using the default ElementTree parser
        tree = ET.parse(manifest_path)
        root = tree.getroot()
    except ET.ParseError as e:
        print(f"{CLR_RED}Error parsing XML file '{manifest_path}': {e}{CLR_RESET}")
        return
    except Exception as e: # Catch other potential file reading/parsing issues
        print(f"{CLR_RED}Error processing file '{manifest_path}': {e}{CLR_RESET}")
        return

    # Extract key info needed for analysis
    target_sdk = get_target_sdk_version(root)
    app_permission = get_application_permission(root)

    print(f"{CLR_CYAN}Extracting information... (Target SDK: {target_sdk}){CLR_RESET}")
    deeplinks = extract_deeplinks(root)
    components_info = extract_components_info(root, target_sdk, app_permission)
    custom_permissions = extract_custom_permissions(root)

    # --- Augment Deeplinks with Potential Params from Smali ---
    print(f"{CLR_CYAN}Scanning Smali for potential deeplink parameters (heuristic)...{CLR_RESET}")
    # Create a map for quick lookup of component -> deeplink list
    deeplinks_by_component = defaultdict(list)
    for link in deeplinks:
        # Only scan for params if it's a URI scheme link and has a component
        if link['scheme'] and link['component'] != "Unknown Component":
            deeplinks_by_component[link['component']].append(link)

    # Iterate through unique components targeted by deeplinks
    unique_components = set(deeplinks_by_component.keys())
    for component_name in unique_components:
        smali_files = find_smali_files(dir_path, component_name)
        component_params = set()
        if not smali_files:
             print(f"{CLR_YELLOW}Warning:{CLR_RESET} No Smali file found for component: {component_name}", file=sys.stderr)
        for smali_file in smali_files:
             # print(f"DEBUG: Scanning {smali_file} for params...") # Optional debug print
             found_in_file = find_query_parameters_in_smali(smali_file)
             component_params.update(found_in_file)

        # Add found parameters back to all deeplink entries targeting this component
        if component_params:
            for link in deeplinks_by_component[component_name]:
                link['potential_params'] = component_params # Assign the found set


    # Format and display results
    format_output(deeplinks, components_info, custom_permissions, target_sdk)


# --- Entry Point ---

def main():
    # Set default encoding to handle potential weird characters
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

    if len(sys.argv) < 2:
        print(f"{CLR_RED}Usage: python {sys.argv[0]} <path/to/apktool_decompiled_directory>{CLR_RESET}")
        sys.exit(1)

    dir_path = sys.argv[1]

    if not os.path.isdir(dir_path):
        print(f"{CLR_RED}Error: Provided path '{dir_path}' is not a valid directory.{CLR_RESET}")
        sys.exit(1)

    analyze_apktool_directory(dir_path)

if __name__ == '__main__':
    main()
